# Spring Boot configuration
spring:
  config:
    import: env.properties
  profiles:
    active: dev
  application:
    name: tinyurl
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/tinyurl.tinyurl-performance?authSource=admin
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
  cache:
    type: ${CACHE_TYPE:redis}
